export const ErrorCode = {
  // Authentication Errors
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_ACCOUNT_DEACTIVATED: "AUTH_ACCOUNT_DEACTIVATED",
  AUTH_NOT_FOUND: "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_REQUESTS: "AUTH_TOO_MANY_REQUESTS",
  AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
  AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_INCORRECT_PASSWORD: "AUTH_INCORRECT_PASSWORD",

  // User Errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",

  // Ticket Errors
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_NOT_AVAILABLE: "TICKET_NOT_AVAILABLE",
  TICKET_HAS_PURCHASES: "TICKET_HAS_PURCHASES",
  TICKET_ALREADY_PURCHASED: "TICKET_ALREADY_PURCHASED",
  INSUFFICIENT_TICKETS: "INSUFFICIENT_TICKETS",
  EVENT_PAST_DATE: "EVENT_PAST_DATE",
  INVALID_EVENT_DATE: "INVALID_EVENT_DATE",
  INVALID_PRICING: "INVALID_PRICING",
  INVALID_AVAILABILITY: "INVALID_AVAILABILITY",
  EXCEEDS_VENUE_CAPACITY: "EXCEEDS_VENUE_CAPACITY",
  INVALID_TOTAL_TICKETS: "INVALID_TOTAL_TICKETS",

  // General Errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
};
